/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AjutorComandaRouteImport } from './routes/ajutor-comanda'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ComenzileMeleRouteImport } from './routes/comenzile-mele'
import { Route as ConfidentialitateRouteImport } from './routes/confidentialitate'
import { Route as ContRouteImport } from './routes/cont'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CosRouteImport } from './routes/cos'
import { Route as DespreRouteImport } from './routes/despre'
import { Route as LivrareRouteImport } from './routes/livrare'
import { Route as MagazinRouteImport } from './routes/magazin'
import { Route as ParolaNouaRouteImport } from './routes/parola-noua'
import { Route as ProduseRouteImport } from './routes/produse'
import { Route as ReturRouteImport } from './routes/retur'
import { Route as RetururiRouteImport } from './routes/retururi'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as TermeniRouteImport } from './routes/termeni'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminClientiRouteImport } from './routes/admin.clienti'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminGuideRouteImport } from './routes/admin.guide'
import { Route as AdminMesajeRouteImport } from './routes/admin.mesaje'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminRetururiRouteImport } from './routes/admin.retururi'
import { Route as AdminRoluriRouteImport } from './routes/admin.roluri'
import { Route as AdminSetariRouteImport } from './routes/admin.setari'
import { Route as AdminStocRouteImport } from './routes/admin.stoc'
import { Route as CategorieSlugRouteImport } from './routes/categorie.$slug'
import { Route as ComandaNumberRouteImport } from './routes/comanda.$number'
import { Route as ProdusSlugRouteImport } from './routes/produs.$slug'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as StaffCategoriiRouteImport } from './routes/staff.categorii'
import { Route as StaffComenziRouteImport } from './routes/staff.comenzi'
import { Route as StaffContinutRouteImport } from './routes/staff.continut'
import { Route as StaffMesajeRouteImport } from './routes/staff.mesaje'
import { Route as StaffProduseRouteImport } from './routes/staff.produse'
import { Route as StaffRetururiRouteImport } from './routes/staff.retururi'
import { Route as StaffStocRouteImport } from './routes/staff.stoc'
import { Route as ApiPublicImgSplatRouteImport } from './routes/api/public/img.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AjutorComandaRoute = AjutorComandaRouteImport.update({
  id: '/ajutor-comanda',
  path: '/ajutor-comanda',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ComenzileMeleRoute = ComenzileMeleRouteImport.update({
  id: '/comenzile-mele',
  path: '/comenzile-mele',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialitateRoute = ConfidentialitateRouteImport.update({
  id: '/confidentialitate',
  path: '/confidentialitate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContRoute = ContRouteImport.update({
  id: '/cont',
  path: '/cont',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CosRoute = CosRouteImport.update({
  id: '/cos',
  path: '/cos',
  getParentRoute: () => rootRouteImport,
} as any)
const DespreRoute = DespreRouteImport.update({
  id: '/despre',
  path: '/despre',
  getParentRoute: () => rootRouteImport,
} as any)
const LivrareRoute = LivrareRouteImport.update({
  id: '/livrare',
  path: '/livrare',
  getParentRoute: () => rootRouteImport,
} as any)
const MagazinRoute = MagazinRouteImport.update({
  id: '/magazin',
  path: '/magazin',
  getParentRoute: () => rootRouteImport,
} as any)
const ParolaNouaRoute = ParolaNouaRouteImport.update({
  id: '/parola-noua',
  path: '/parola-noua',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduseRoute = ProduseRouteImport.update({
  id: '/produse',
  path: '/produse',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturRoute = ReturRouteImport.update({
  id: '/retur',
  path: '/retur',
  getParentRoute: () => rootRouteImport,
} as any)
const RetururiRoute = RetururiRouteImport.update({
  id: '/retururi',
  path: '/retururi',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const TermeniRoute = TermeniRouteImport.update({
  id: '/termeni',
  path: '/termeni',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientiRoute = AdminClientiRouteImport.update({
  id: '/clienti',
  path: '/clienti',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGuideRoute = AdminGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMesajeRoute = AdminMesajeRouteImport.update({
  id: '/mesaje',
  path: '/mesaje',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRetururiRoute = AdminRetururiRouteImport.update({
  id: '/retururi',
  path: '/retururi',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoluriRoute = AdminRoluriRouteImport.update({
  id: '/roluri',
  path: '/roluri',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSetariRoute = AdminSetariRouteImport.update({
  id: '/setari',
  path: '/setari',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStocRoute = AdminStocRouteImport.update({
  id: '/stoc',
  path: '/stoc',
  getParentRoute: () => AdminRoute,
} as any)
const CategorieSlugRoute = CategorieSlugRouteImport.update({
  id: '/categorie/$slug',
  path: '/categorie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ComandaNumberRoute = ComandaNumberRouteImport.update({
  id: '/comanda/$number',
  path: '/comanda/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdusSlugRoute = ProdusSlugRouteImport.update({
  id: '/produs/$slug',
  path: '/produs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffCategoriiRoute = StaffCategoriiRouteImport.update({
  id: '/categorii',
  path: '/categorii',
  getParentRoute: () => StaffRoute,
} as any)
const StaffComenziRoute = StaffComenziRouteImport.update({
  id: '/comenzi',
  path: '/comenzi',
  getParentRoute: () => StaffRoute,
} as any)
const StaffContinutRoute = StaffContinutRouteImport.update({
  id: '/continut',
  path: '/continut',
  getParentRoute: () => StaffRoute,
} as any)
const StaffMesajeRoute = StaffMesajeRouteImport.update({
  id: '/mesaje',
  path: '/mesaje',
  getParentRoute: () => StaffRoute,
} as any)
const StaffProduseRoute = StaffProduseRouteImport.update({
  id: '/produse',
  path: '/produse',
  getParentRoute: () => StaffRoute,
} as any)
const StaffRetururiRoute = StaffRetururiRouteImport.update({
  id: '/retururi',
  path: '/retururi',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStocRoute = StaffStocRouteImport.update({
  id: '/stoc',
  path: '/stoc',
  getParentRoute: () => StaffRoute,
} as any)
const ApiPublicImgSplatRoute = ApiPublicImgSplatRouteImport.update({
  id: '/api/public/img/$',
  path: '/api/public/img/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ajutor-comanda': typeof AjutorComandaRoute
  '/checkout': typeof CheckoutRoute
  '/comenzile-mele': typeof ComenzileMeleRoute
  '/confidentialitate': typeof ConfidentialitateRoute
  '/cont': typeof ContRoute
  '/contact': typeof ContactRoute
  '/cos': typeof CosRoute
  '/despre': typeof DespreRoute
  '/livrare': typeof LivrareRoute
  '/magazin': typeof MagazinRoute
  '/parola-noua': typeof ParolaNouaRoute
  '/produse': typeof ProduseRoute
  '/retur': typeof ReturRoute
  '/retururi': typeof RetururiRoute
  '/staff': typeof StaffRouteWithChildren
  '/termeni': typeof TermeniRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/clienti': typeof AdminClientiRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/guide': typeof AdminGuideRoute
  '/admin/mesaje': typeof AdminMesajeRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/retururi': typeof AdminRetururiRoute
  '/admin/roluri': typeof AdminRoluriRoute
  '/admin/setari': typeof AdminSetariRoute
  '/admin/stoc': typeof AdminStocRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/comanda/$number': typeof ComandaNumberRoute
  '/produs/$slug': typeof ProdusSlugRoute
  '/staff/categorii': typeof StaffCategoriiRoute
  '/staff/comenzi': typeof StaffComenziRoute
  '/staff/continut': typeof StaffContinutRoute
  '/staff/mesaje': typeof StaffMesajeRoute
  '/staff/produse': typeof StaffProduseRoute
  '/staff/retururi': typeof StaffRetururiRoute
  '/staff/stoc': typeof StaffStocRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajutor-comanda': typeof AjutorComandaRoute
  '/checkout': typeof CheckoutRoute
  '/comenzile-mele': typeof ComenzileMeleRoute
  '/confidentialitate': typeof ConfidentialitateRoute
  '/cont': typeof ContRoute
  '/contact': typeof ContactRoute
  '/cos': typeof CosRoute
  '/despre': typeof DespreRoute
  '/livrare': typeof LivrareRoute
  '/magazin': typeof MagazinRoute
  '/parola-noua': typeof ParolaNouaRoute
  '/produse': typeof ProduseRoute
  '/retur': typeof ReturRoute
  '/retururi': typeof RetururiRoute
  '/termeni': typeof TermeniRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/clienti': typeof AdminClientiRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/guide': typeof AdminGuideRoute
  '/admin/mesaje': typeof AdminMesajeRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/retururi': typeof AdminRetururiRoute
  '/admin/roluri': typeof AdminRoluriRoute
  '/admin/setari': typeof AdminSetariRoute
  '/admin/stoc': typeof AdminStocRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/comanda/$number': typeof ComandaNumberRoute
  '/produs/$slug': typeof ProdusSlugRoute
  '/staff/categorii': typeof StaffCategoriiRoute
  '/staff/comenzi': typeof StaffComenziRoute
  '/staff/continut': typeof StaffContinutRoute
  '/staff/mesaje': typeof StaffMesajeRoute
  '/staff/produse': typeof StaffProduseRoute
  '/staff/retururi': typeof StaffRetururiRoute
  '/staff/stoc': typeof StaffStocRoute
  '/admin': typeof AdminIndexRoute
  '/staff': typeof StaffIndexRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ajutor-comanda': typeof AjutorComandaRoute
  '/checkout': typeof CheckoutRoute
  '/comenzile-mele': typeof ComenzileMeleRoute
  '/confidentialitate': typeof ConfidentialitateRoute
  '/cont': typeof ContRoute
  '/contact': typeof ContactRoute
  '/cos': typeof CosRoute
  '/despre': typeof DespreRoute
  '/livrare': typeof LivrareRoute
  '/magazin': typeof MagazinRoute
  '/parola-noua': typeof ParolaNouaRoute
  '/produse': typeof ProduseRoute
  '/retur': typeof ReturRoute
  '/retururi': typeof RetururiRoute
  '/staff': typeof StaffRouteWithChildren
  '/termeni': typeof TermeniRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/clienti': typeof AdminClientiRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/guide': typeof AdminGuideRoute
  '/admin/mesaje': typeof AdminMesajeRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/retururi': typeof AdminRetururiRoute
  '/admin/roluri': typeof AdminRoluriRoute
  '/admin/setari': typeof AdminSetariRoute
  '/admin/stoc': typeof AdminStocRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/comanda/$number': typeof ComandaNumberRoute
  '/produs/$slug': typeof ProdusSlugRoute
  '/staff/categorii': typeof StaffCategoriiRoute
  '/staff/comenzi': typeof StaffComenziRoute
  '/staff/continut': typeof StaffContinutRoute
  '/staff/mesaje': typeof StaffMesajeRoute
  '/staff/produse': typeof StaffProduseRoute
  '/staff/retururi': typeof StaffRetururiRoute
  '/staff/stoc': typeof StaffStocRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ajutor-comanda'
    | '/checkout'
    | '/comenzile-mele'
    | '/confidentialitate'
    | '/cont'
    | '/contact'
    | '/cos'
    | '/despre'
    | '/livrare'
    | '/magazin'
    | '/parola-noua'
    | '/produse'
    | '/retur'
    | '/retururi'
    | '/staff'
    | '/termeni'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/clienti'
    | '/admin/content'
    | '/admin/guide'
    | '/admin/mesaje'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/retururi'
    | '/admin/roluri'
    | '/admin/setari'
    | '/admin/stoc'
    | '/categorie/$slug'
    | '/comanda/$number'
    | '/produs/$slug'
    | '/staff/categorii'
    | '/staff/comenzi'
    | '/staff/continut'
    | '/staff/mesaje'
    | '/staff/produse'
    | '/staff/retururi'
    | '/staff/stoc'
    | '/admin/'
    | '/staff/'
    | '/api/public/img/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajutor-comanda'
    | '/checkout'
    | '/comenzile-mele'
    | '/confidentialitate'
    | '/cont'
    | '/contact'
    | '/cos'
    | '/despre'
    | '/livrare'
    | '/magazin'
    | '/parola-noua'
    | '/produse'
    | '/retur'
    | '/retururi'
    | '/termeni'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/clienti'
    | '/admin/content'
    | '/admin/guide'
    | '/admin/mesaje'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/retururi'
    | '/admin/roluri'
    | '/admin/setari'
    | '/admin/stoc'
    | '/categorie/$slug'
    | '/comanda/$number'
    | '/produs/$slug'
    | '/staff/categorii'
    | '/staff/comenzi'
    | '/staff/continut'
    | '/staff/mesaje'
    | '/staff/produse'
    | '/staff/retururi'
    | '/staff/stoc'
    | '/admin'
    | '/staff'
    | '/api/public/img/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ajutor-comanda'
    | '/checkout'
    | '/comenzile-mele'
    | '/confidentialitate'
    | '/cont'
    | '/contact'
    | '/cos'
    | '/despre'
    | '/livrare'
    | '/magazin'
    | '/parola-noua'
    | '/produse'
    | '/retur'
    | '/retururi'
    | '/staff'
    | '/termeni'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/clienti'
    | '/admin/content'
    | '/admin/guide'
    | '/admin/mesaje'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/retururi'
    | '/admin/roluri'
    | '/admin/setari'
    | '/admin/stoc'
    | '/categorie/$slug'
    | '/comanda/$number'
    | '/produs/$slug'
    | '/staff/categorii'
    | '/staff/comenzi'
    | '/staff/continut'
    | '/staff/mesaje'
    | '/staff/produse'
    | '/staff/retururi'
    | '/staff/stoc'
    | '/admin/'
    | '/staff/'
    | '/api/public/img/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AjutorComandaRoute: typeof AjutorComandaRoute
  CheckoutRoute: typeof CheckoutRoute
  ComenzileMeleRoute: typeof ComenzileMeleRoute
  ConfidentialitateRoute: typeof ConfidentialitateRoute
  ContRoute: typeof ContRoute
  ContactRoute: typeof ContactRoute
  CosRoute: typeof CosRoute
  DespreRoute: typeof DespreRoute
  LivrareRoute: typeof LivrareRoute
  MagazinRoute: typeof MagazinRoute
  ParolaNouaRoute: typeof ParolaNouaRoute
  ProduseRoute: typeof ProduseRoute
  ReturRoute: typeof ReturRoute
  RetururiRoute: typeof RetururiRoute
  StaffRoute: typeof StaffRouteWithChildren
  TermeniRoute: typeof TermeniRoute
  CategorieSlugRoute: typeof CategorieSlugRoute
  ComandaNumberRoute: typeof ComandaNumberRoute
  ProdusSlugRoute: typeof ProdusSlugRoute
  ApiPublicImgSplatRoute: typeof ApiPublicImgSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajutor-comanda': {
      id: '/ajutor-comanda'
      path: '/ajutor-comanda'
      fullPath: '/ajutor-comanda'
      preLoaderRoute: typeof AjutorComandaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comenzile-mele': {
      id: '/comenzile-mele'
      path: '/comenzile-mele'
      fullPath: '/comenzile-mele'
      preLoaderRoute: typeof ComenzileMeleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialitate': {
      id: '/confidentialitate'
      path: '/confidentialitate'
      fullPath: '/confidentialitate'
      preLoaderRoute: typeof ConfidentialitateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cont': {
      id: '/cont'
      path: '/cont'
      fullPath: '/cont'
      preLoaderRoute: typeof ContRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cos': {
      id: '/cos'
      path: '/cos'
      fullPath: '/cos'
      preLoaderRoute: typeof CosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despre': {
      id: '/despre'
      path: '/despre'
      fullPath: '/despre'
      preLoaderRoute: typeof DespreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livrare': {
      id: '/livrare'
      path: '/livrare'
      fullPath: '/livrare'
      preLoaderRoute: typeof LivrareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magazin': {
      id: '/magazin'
      path: '/magazin'
      fullPath: '/magazin'
      preLoaderRoute: typeof MagazinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parola-noua': {
      id: '/parola-noua'
      path: '/parola-noua'
      fullPath: '/parola-noua'
      preLoaderRoute: typeof ParolaNouaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produse': {
      id: '/produse'
      path: '/produse'
      fullPath: '/produse'
      preLoaderRoute: typeof ProduseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retur': {
      id: '/retur'
      path: '/retur'
      fullPath: '/retur'
      preLoaderRoute: typeof ReturRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retururi': {
      id: '/retururi'
      path: '/retururi'
      fullPath: '/retururi'
      preLoaderRoute: typeof RetururiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termeni': {
      id: '/termeni'
      path: '/termeni'
      fullPath: '/termeni'
      preLoaderRoute: typeof TermeniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clienti': {
      id: '/admin/clienti'
      path: '/clienti'
      fullPath: '/admin/clienti'
      preLoaderRoute: typeof AdminClientiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/guide': {
      id: '/admin/guide'
      path: '/guide'
      fullPath: '/admin/guide'
      preLoaderRoute: typeof AdminGuideRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mesaje': {
      id: '/admin/mesaje'
      path: '/mesaje'
      fullPath: '/admin/mesaje'
      preLoaderRoute: typeof AdminMesajeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/retururi': {
      id: '/admin/retururi'
      path: '/retururi'
      fullPath: '/admin/retururi'
      preLoaderRoute: typeof AdminRetururiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roluri': {
      id: '/admin/roluri'
      path: '/roluri'
      fullPath: '/admin/roluri'
      preLoaderRoute: typeof AdminRoluriRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/setari': {
      id: '/admin/setari'
      path: '/setari'
      fullPath: '/admin/setari'
      preLoaderRoute: typeof AdminSetariRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stoc': {
      id: '/admin/stoc'
      path: '/stoc'
      fullPath: '/admin/stoc'
      preLoaderRoute: typeof AdminStocRouteImport
      parentRoute: typeof AdminRoute
    }
    '/categorie/$slug': {
      id: '/categorie/$slug'
      path: '/categorie/$slug'
      fullPath: '/categorie/$slug'
      preLoaderRoute: typeof CategorieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comanda/$number': {
      id: '/comanda/$number'
      path: '/comanda/$number'
      fullPath: '/comanda/$number'
      preLoaderRoute: typeof ComandaNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produs/$slug': {
      id: '/produs/$slug'
      path: '/produs/$slug'
      fullPath: '/produs/$slug'
      preLoaderRoute: typeof ProdusSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/categorii': {
      id: '/staff/categorii'
      path: '/categorii'
      fullPath: '/staff/categorii'
      preLoaderRoute: typeof StaffCategoriiRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/comenzi': {
      id: '/staff/comenzi'
      path: '/comenzi'
      fullPath: '/staff/comenzi'
      preLoaderRoute: typeof StaffComenziRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/continut': {
      id: '/staff/continut'
      path: '/continut'
      fullPath: '/staff/continut'
      preLoaderRoute: typeof StaffContinutRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/mesaje': {
      id: '/staff/mesaje'
      path: '/mesaje'
      fullPath: '/staff/mesaje'
      preLoaderRoute: typeof StaffMesajeRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/produse': {
      id: '/staff/produse'
      path: '/produse'
      fullPath: '/staff/produse'
      preLoaderRoute: typeof StaffProduseRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/retururi': {
      id: '/staff/retururi'
      path: '/retururi'
      fullPath: '/staff/retururi'
      preLoaderRoute: typeof StaffRetururiRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/stoc': {
      id: '/staff/stoc'
      path: '/stoc'
      fullPath: '/staff/stoc'
      preLoaderRoute: typeof StaffStocRouteImport
      parentRoute: typeof StaffRoute
    }
    '/api/public/img/$': {
      id: '/api/public/img/$'
      path: '/api/public/img/$'
      fullPath: '/api/public/img/$'
      preLoaderRoute: typeof ApiPublicImgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminClientiRoute: typeof AdminClientiRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminGuideRoute: typeof AdminGuideRoute
  AdminMesajeRoute: typeof AdminMesajeRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminRetururiRoute: typeof AdminRetururiRoute
  AdminRoluriRoute: typeof AdminRoluriRoute
  AdminSetariRoute: typeof AdminSetariRoute
  AdminStocRoute: typeof AdminStocRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminClientiRoute: AdminClientiRoute,
  AdminContentRoute: AdminContentRoute,
  AdminGuideRoute: AdminGuideRoute,
  AdminMesajeRoute: AdminMesajeRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminRetururiRoute: AdminRetururiRoute,
  AdminRoluriRoute: AdminRoluriRoute,
  AdminSetariRoute: AdminSetariRoute,
  AdminStocRoute: AdminStocRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StaffRouteChildren {
  StaffCategoriiRoute: typeof StaffCategoriiRoute
  StaffComenziRoute: typeof StaffComenziRoute
  StaffContinutRoute: typeof StaffContinutRoute
  StaffMesajeRoute: typeof StaffMesajeRoute
  StaffProduseRoute: typeof StaffProduseRoute
  StaffRetururiRoute: typeof StaffRetururiRoute
  StaffStocRoute: typeof StaffStocRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffCategoriiRoute: StaffCategoriiRoute,
  StaffComenziRoute: StaffComenziRoute,
  StaffContinutRoute: StaffContinutRoute,
  StaffMesajeRoute: StaffMesajeRoute,
  StaffProduseRoute: StaffProduseRoute,
  StaffRetururiRoute: StaffRetururiRoute,
  StaffStocRoute: StaffStocRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AjutorComandaRoute: AjutorComandaRoute,
  CheckoutRoute: CheckoutRoute,
  ComenzileMeleRoute: ComenzileMeleRoute,
  ConfidentialitateRoute: ConfidentialitateRoute,
  ContRoute: ContRoute,
  ContactRoute: ContactRoute,
  CosRoute: CosRoute,
  DespreRoute: DespreRoute,
  LivrareRoute: LivrareRoute,
  MagazinRoute: MagazinRoute,
  ParolaNouaRoute: ParolaNouaRoute,
  ProduseRoute: ProduseRoute,
  ReturRoute: ReturRoute,
  RetururiRoute: RetururiRoute,
  StaffRoute: StaffRouteWithChildren,
  TermeniRoute: TermeniRoute,
  CategorieSlugRoute: CategorieSlugRoute,
  ComandaNumberRoute: ComandaNumberRoute,
  ProdusSlugRoute: ProdusSlugRoute,
  ApiPublicImgSplatRoute: ApiPublicImgSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
