/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ConfidentialitateRouteImport } from './routes/confidentialitate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CosRouteImport } from './routes/cos'
import { Route as DespreRouteImport } from './routes/despre'
import { Route as LivrareRouteImport } from './routes/livrare'
import { Route as ProduseRouteImport } from './routes/produse'
import { Route as ReturRouteImport } from './routes/retur'
import { Route as TermeniRouteImport } from './routes/termeni'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminGuideRouteImport } from './routes/admin.guide'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as CategorieSlugRouteImport } from './routes/categorie.$slug'
import { Route as ComandaNumberRouteImport } from './routes/comanda.$number'
import { Route as ProdusSlugRouteImport } from './routes/produs.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialitateRoute = ConfidentialitateRouteImport.update({
  id: '/confidentialitate',
  path: '/confidentialitate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CosRoute = CosRouteImport.update({
  id: '/cos',
  path: '/cos',
  getParentRoute: () => rootRouteImport,
} as any)
const DespreRoute = DespreRouteImport.update({
  id: '/despre',
  path: '/despre',
  getParentRoute: () => rootRouteImport,
} as any)
const LivrareRoute = LivrareRouteImport.update({
  id: '/livrare',
  path: '/livrare',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduseRoute = ProduseRouteImport.update({
  id: '/produse',
  path: '/produse',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturRoute = ReturRouteImport.update({
  id: '/retur',
  path: '/retur',
  getParentRoute: () => rootRouteImport,
} as any)
const TermeniRoute = TermeniRouteImport.update({
  id: '/termeni',
  path: '/termeni',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGuideRoute = AdminGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const CategorieSlugRoute = CategorieSlugRouteImport.update({
  id: '/categorie/$slug',
  path: '/categorie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ComandaNumberRoute = ComandaNumberRouteImport.update({
  id: '/comanda/$number',
  path: '/comanda/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdusSlugRoute = ProdusSlugRouteImport.update({
  id: '/produs/$slug',
  path: '/produs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/confidentialitate': typeof ConfidentialitateRoute
  '/contact': typeof ContactRoute
  '/cos': typeof CosRoute
  '/despre': typeof DespreRoute
  '/livrare': typeof LivrareRoute
  '/produse': typeof ProduseRoute
  '/retur': typeof ReturRoute
  '/termeni': typeof TermeniRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/guide': typeof AdminGuideRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/comanda/$number': typeof ComandaNumberRoute
  '/produs/$slug': typeof ProdusSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/confidentialitate': typeof ConfidentialitateRoute
  '/contact': typeof ContactRoute
  '/cos': typeof CosRoute
  '/despre': typeof DespreRoute
  '/livrare': typeof LivrareRoute
  '/produse': typeof ProduseRoute
  '/retur': typeof ReturRoute
  '/termeni': typeof TermeniRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/guide': typeof AdminGuideRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/comanda/$number': typeof ComandaNumberRoute
  '/produs/$slug': typeof ProdusSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/confidentialitate': typeof ConfidentialitateRoute
  '/contact': typeof ContactRoute
  '/cos': typeof CosRoute
  '/despre': typeof DespreRoute
  '/livrare': typeof LivrareRoute
  '/produse': typeof ProduseRoute
  '/retur': typeof ReturRoute
  '/termeni': typeof TermeniRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/guide': typeof AdminGuideRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/comanda/$number': typeof ComandaNumberRoute
  '/produs/$slug': typeof ProdusSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/confidentialitate'
    | '/contact'
    | '/cos'
    | '/despre'
    | '/livrare'
    | '/produse'
    | '/retur'
    | '/termeni'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/guide'
    | '/admin/orders'
    | '/admin/products'
    | '/categorie/$slug'
    | '/comanda/$number'
    | '/produs/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/confidentialitate'
    | '/contact'
    | '/cos'
    | '/despre'
    | '/livrare'
    | '/produse'
    | '/retur'
    | '/termeni'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/guide'
    | '/admin/orders'
    | '/admin/products'
    | '/categorie/$slug'
    | '/comanda/$number'
    | '/produs/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/confidentialitate'
    | '/contact'
    | '/cos'
    | '/despre'
    | '/livrare'
    | '/produse'
    | '/retur'
    | '/termeni'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/guide'
    | '/admin/orders'
    | '/admin/products'
    | '/categorie/$slug'
    | '/comanda/$number'
    | '/produs/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  ConfidentialitateRoute: typeof ConfidentialitateRoute
  ContactRoute: typeof ContactRoute
  CosRoute: typeof CosRoute
  DespreRoute: typeof DespreRoute
  LivrareRoute: typeof LivrareRoute
  ProduseRoute: typeof ProduseRoute
  ReturRoute: typeof ReturRoute
  TermeniRoute: typeof TermeniRoute
  CategorieSlugRoute: typeof CategorieSlugRoute
  ComandaNumberRoute: typeof ComandaNumberRoute
  ProdusSlugRoute: typeof ProdusSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialitate': {
      id: '/confidentialitate'
      path: '/confidentialitate'
      fullPath: '/confidentialitate'
      preLoaderRoute: typeof ConfidentialitateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cos': {
      id: '/cos'
      path: '/cos'
      fullPath: '/cos'
      preLoaderRoute: typeof CosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despre': {
      id: '/despre'
      path: '/despre'
      fullPath: '/despre'
      preLoaderRoute: typeof DespreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livrare': {
      id: '/livrare'
      path: '/livrare'
      fullPath: '/livrare'
      preLoaderRoute: typeof LivrareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produse': {
      id: '/produse'
      path: '/produse'
      fullPath: '/produse'
      preLoaderRoute: typeof ProduseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retur': {
      id: '/retur'
      path: '/retur'
      fullPath: '/retur'
      preLoaderRoute: typeof ReturRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termeni': {
      id: '/termeni'
      path: '/termeni'
      fullPath: '/termeni'
      preLoaderRoute: typeof TermeniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/guide': {
      id: '/admin/guide'
      path: '/guide'
      fullPath: '/admin/guide'
      preLoaderRoute: typeof AdminGuideRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/categorie/$slug': {
      id: '/categorie/$slug'
      path: '/categorie/$slug'
      fullPath: '/categorie/$slug'
      preLoaderRoute: typeof CategorieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comanda/$number': {
      id: '/comanda/$number'
      path: '/comanda/$number'
      fullPath: '/comanda/$number'
      preLoaderRoute: typeof ComandaNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produs/$slug': {
      id: '/produs/$slug'
      path: '/produs/$slug'
      fullPath: '/produs/$slug'
      preLoaderRoute: typeof ProdusSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminGuideRoute: typeof AdminGuideRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminContentRoute: AdminContentRoute,
  AdminGuideRoute: AdminGuideRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  ConfidentialitateRoute: ConfidentialitateRoute,
  ContactRoute: ContactRoute,
  CosRoute: CosRoute,
  DespreRoute: DespreRoute,
  LivrareRoute: LivrareRoute,
  ProduseRoute: ProduseRoute,
  ReturRoute: ReturRoute,
  TermeniRoute: TermeniRoute,
  CategorieSlugRoute: CategorieSlugRoute,
  ComandaNumberRoute: ComandaNumberRoute,
  ProdusSlugRoute: ProdusSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
