/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AjutorComandaRouteImport } from './routes/ajutor-comanda'
import { Route as AutentificareRouteImport } from './routes/autentificare'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ComenzileMeleRouteImport } from './routes/comenzile-mele'
import { Route as ConfidentialitateRouteImport } from './routes/confidentialitate'
import { Route as ContRouteImport } from './routes/cont'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CosRouteImport } from './routes/cos'
import { Route as DespreRouteImport } from './routes/despre'
import { Route as DezabonareRouteImport } from './routes/dezabonare'
import { Route as LivrareRouteImport } from './routes/livrare'
import { Route as MagazinRouteImport } from './routes/magazin'
import { Route as N7q4V2m9RouteImport } from './routes/n7q4-v2m9'
import { Route as ParolaNouaRouteImport } from './routes/parola-noua'
import { Route as ProduseRouteImport } from './routes/produse'
import { Route as ResetareParolaRouteImport } from './routes/resetare-parola'
import { Route as ReturRouteImport } from './routes/retur'
import { Route as RetururiRouteImport } from './routes/retururi'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as TermeniRouteImport } from './routes/termeni'
import { Route as CategorieSlugRouteImport } from './routes/categorie.$slug'
import { Route as ComandaNumberRouteImport } from './routes/comanda.$number'
import { Route as N7q4V2m9IndexRouteImport } from './routes/n7q4-v2m9.index'
import { Route as N7q4V2m9AuditRouteImport } from './routes/n7q4-v2m9.audit'
import { Route as N7q4V2m9CategoriesRouteImport } from './routes/n7q4-v2m9.categories'
import { Route as N7q4V2m9ClientiRouteImport } from './routes/n7q4-v2m9.clienti'
import { Route as N7q4V2m9ContentRouteImport } from './routes/n7q4-v2m9.content'
import { Route as N7q4V2m9GuideRouteImport } from './routes/n7q4-v2m9.guide'
import { Route as N7q4V2m9MesajeRouteImport } from './routes/n7q4-v2m9.mesaje'
import { Route as N7q4V2m9OrdersRouteImport } from './routes/n7q4-v2m9.orders'
import { Route as N7q4V2m9ProductsRouteImport } from './routes/n7q4-v2m9.products'
import { Route as N7q4V2m9RetururiRouteImport } from './routes/n7q4-v2m9.retururi'
import { Route as N7q4V2m9RoluriRouteImport } from './routes/n7q4-v2m9.roluri'
import { Route as N7q4V2m9SetariRouteImport } from './routes/n7q4-v2m9.setari'
import { Route as N7q4V2m9StocRouteImport } from './routes/n7q4-v2m9.stoc'
import { Route as N7q4V2m9UtilizatoriRouteImport } from './routes/n7q4-v2m9.utilizatori'
import { Route as ProdusSlugRouteImport } from './routes/produs.$slug'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as StaffCategoriiRouteImport } from './routes/staff.categorii'
import { Route as StaffComenziRouteImport } from './routes/staff.comenzi'
import { Route as StaffMesajeRouteImport } from './routes/staff.mesaje'
import { Route as StaffProduseRouteImport } from './routes/staff.produse'
import { Route as StaffRetururiRouteImport } from './routes/staff.retururi'
import { Route as StaffStocRouteImport } from './routes/staff.stoc'
import { Route as ApiAuthLoginRouteImport } from './routes/api.auth.login'
import { Route as ApiAuthPasswordResetRouteImport } from './routes/api.auth.password-reset'
import { Route as ApiPublicImgSplatRouteImport } from './routes/api/public/img.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AjutorComandaRoute = AjutorComandaRouteImport.update({
  id: '/ajutor-comanda',
  path: '/ajutor-comanda',
  getParentRoute: () => rootRouteImport,
} as any)
const AutentificareRoute = AutentificareRouteImport.update({
  id: '/autentificare',
  path: '/autentificare',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ComenzileMeleRoute = ComenzileMeleRouteImport.update({
  id: '/comenzile-mele',
  path: '/comenzile-mele',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialitateRoute = ConfidentialitateRouteImport.update({
  id: '/confidentialitate',
  path: '/confidentialitate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContRoute = ContRouteImport.update({
  id: '/cont',
  path: '/cont',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CosRoute = CosRouteImport.update({
  id: '/cos',
  path: '/cos',
  getParentRoute: () => rootRouteImport,
} as any)
const DespreRoute = DespreRouteImport.update({
  id: '/despre',
  path: '/despre',
  getParentRoute: () => rootRouteImport,
} as any)
const DezabonareRoute = DezabonareRouteImport.update({
  id: '/dezabonare',
  path: '/dezabonare',
  getParentRoute: () => rootRouteImport,
} as any)
const LivrareRoute = LivrareRouteImport.update({
  id: '/livrare',
  path: '/livrare',
  getParentRoute: () => rootRouteImport,
} as any)
const MagazinRoute = MagazinRouteImport.update({
  id: '/magazin',
  path: '/magazin',
  getParentRoute: () => rootRouteImport,
} as any)
const N7q4V2m9Route = N7q4V2m9RouteImport.update({
  id: '/n7q4-v2m9',
  path: '/n7q4-v2m9',
  getParentRoute: () => rootRouteImport,
} as any)
const ParolaNouaRoute = ParolaNouaRouteImport.update({
  id: '/parola-noua',
  path: '/parola-noua',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduseRoute = ProduseRouteImport.update({
  id: '/produse',
  path: '/produse',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetareParolaRoute = ResetareParolaRouteImport.update({
  id: '/resetare-parola',
  path: '/resetare-parola',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturRoute = ReturRouteImport.update({
  id: '/retur',
  path: '/retur',
  getParentRoute: () => rootRouteImport,
} as any)
const RetururiRoute = RetururiRouteImport.update({
  id: '/retururi',
  path: '/retururi',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const TermeniRoute = TermeniRouteImport.update({
  id: '/termeni',
  path: '/termeni',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorieSlugRoute = CategorieSlugRouteImport.update({
  id: '/categorie/$slug',
  path: '/categorie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ComandaNumberRoute = ComandaNumberRouteImport.update({
  id: '/comanda/$number',
  path: '/comanda/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const N7q4V2m9IndexRoute = N7q4V2m9IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => N7q4V2m9Route,
} as any)
const N7q4V2m9AuditRoute = N7q4V2m9AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => N7q4V2m9Route,
} as any)
const N7q4V2m9CategoriesRoute = N7q4V2m9CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => N7q4V2m9Route,
} as any)
const N7q4V2m9ClientiRoute = N7q4V2m9ClientiRouteImport.update({
  id: '/clienti',
  path: '/clienti',
  getParentRoute: () => N7q4V2m9Route,
} as any)
const N7q4V2m9ContentRoute = N7q4V2m9ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => N7q4V2m9Route,
} as any)
const N7q4V2m9GuideRoute = N7q4V2m9GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => N7q4V2m9Route,
} as any)
const N7q4V2m9MesajeRoute = N7q4V2m9MesajeRouteImport.update({
  id: '/mesaje',
  path: '/mesaje',
  getParentRoute: () => N7q4V2m9Route,
} as any)
const N7q4V2m9OrdersRoute = N7q4V2m9OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => N7q4V2m9Route,
} as any)
const N7q4V2m9ProductsRoute = N7q4V2m9ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => N7q4V2m9Route,
} as any)
const N7q4V2m9RetururiRoute = N7q4V2m9RetururiRouteImport.update({
  id: '/retururi',
  path: '/retururi',
  getParentRoute: () => N7q4V2m9Route,
} as any)
const N7q4V2m9RoluriRoute = N7q4V2m9RoluriRouteImport.update({
  id: '/roluri',
  path: '/roluri',
  getParentRoute: () => N7q4V2m9Route,
} as any)
const N7q4V2m9SetariRoute = N7q4V2m9SetariRouteImport.update({
  id: '/setari',
  path: '/setari',
  getParentRoute: () => N7q4V2m9Route,
} as any)
const N7q4V2m9StocRoute = N7q4V2m9StocRouteImport.update({
  id: '/stoc',
  path: '/stoc',
  getParentRoute: () => N7q4V2m9Route,
} as any)
const N7q4V2m9UtilizatoriRoute = N7q4V2m9UtilizatoriRouteImport.update({
  id: '/utilizatori',
  path: '/utilizatori',
  getParentRoute: () => N7q4V2m9Route,
} as any)
const ProdusSlugRoute = ProdusSlugRouteImport.update({
  id: '/produs/$slug',
  path: '/produs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffCategoriiRoute = StaffCategoriiRouteImport.update({
  id: '/categorii',
  path: '/categorii',
  getParentRoute: () => StaffRoute,
} as any)
const StaffComenziRoute = StaffComenziRouteImport.update({
  id: '/comenzi',
  path: '/comenzi',
  getParentRoute: () => StaffRoute,
} as any)
const StaffMesajeRoute = StaffMesajeRouteImport.update({
  id: '/mesaje',
  path: '/mesaje',
  getParentRoute: () => StaffRoute,
} as any)
const StaffProduseRoute = StaffProduseRouteImport.update({
  id: '/produse',
  path: '/produse',
  getParentRoute: () => StaffRoute,
} as any)
const StaffRetururiRoute = StaffRetururiRouteImport.update({
  id: '/retururi',
  path: '/retururi',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStocRoute = StaffStocRouteImport.update({
  id: '/stoc',
  path: '/stoc',
  getParentRoute: () => StaffRoute,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthPasswordResetRoute = ApiAuthPasswordResetRouteImport.update({
  id: '/api/auth/password-reset',
  path: '/api/auth/password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImgSplatRoute = ApiPublicImgSplatRouteImport.update({
  id: '/api/public/img/$',
  path: '/api/public/img/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ajutor-comanda': typeof AjutorComandaRoute
  '/autentificare': typeof AutentificareRoute
  '/checkout': typeof CheckoutRoute
  '/comenzile-mele': typeof ComenzileMeleRoute
  '/confidentialitate': typeof ConfidentialitateRoute
  '/cont': typeof ContRoute
  '/contact': typeof ContactRoute
  '/cos': typeof CosRoute
  '/despre': typeof DespreRoute
  '/dezabonare': typeof DezabonareRoute
  '/livrare': typeof LivrareRoute
  '/magazin': typeof MagazinRoute
  '/n7q4-v2m9': typeof N7q4V2m9RouteWithChildren
  '/parola-noua': typeof ParolaNouaRoute
  '/produse': typeof ProduseRoute
  '/resetare-parola': typeof ResetareParolaRoute
  '/retur': typeof ReturRoute
  '/retururi': typeof RetururiRoute
  '/staff': typeof StaffRouteWithChildren
  '/termeni': typeof TermeniRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/comanda/$number': typeof ComandaNumberRoute
  '/n7q4-v2m9/audit': typeof N7q4V2m9AuditRoute
  '/n7q4-v2m9/categories': typeof N7q4V2m9CategoriesRoute
  '/n7q4-v2m9/clienti': typeof N7q4V2m9ClientiRoute
  '/n7q4-v2m9/content': typeof N7q4V2m9ContentRoute
  '/n7q4-v2m9/guide': typeof N7q4V2m9GuideRoute
  '/n7q4-v2m9/mesaje': typeof N7q4V2m9MesajeRoute
  '/n7q4-v2m9/orders': typeof N7q4V2m9OrdersRoute
  '/n7q4-v2m9/products': typeof N7q4V2m9ProductsRoute
  '/n7q4-v2m9/retururi': typeof N7q4V2m9RetururiRoute
  '/n7q4-v2m9/roluri': typeof N7q4V2m9RoluriRoute
  '/n7q4-v2m9/setari': typeof N7q4V2m9SetariRoute
  '/n7q4-v2m9/stoc': typeof N7q4V2m9StocRoute
  '/n7q4-v2m9/utilizatori': typeof N7q4V2m9UtilizatoriRoute
  '/produs/$slug': typeof ProdusSlugRoute
  '/staff/categorii': typeof StaffCategoriiRoute
  '/staff/comenzi': typeof StaffComenziRoute
  '/staff/mesaje': typeof StaffMesajeRoute
  '/staff/produse': typeof StaffProduseRoute
  '/staff/retururi': typeof StaffRetururiRoute
  '/staff/stoc': typeof StaffStocRoute
  '/n7q4-v2m9/': typeof N7q4V2m9IndexRoute
  '/staff/': typeof StaffIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/password-reset': typeof ApiAuthPasswordResetRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ajutor-comanda': typeof AjutorComandaRoute
  '/autentificare': typeof AutentificareRoute
  '/checkout': typeof CheckoutRoute
  '/comenzile-mele': typeof ComenzileMeleRoute
  '/confidentialitate': typeof ConfidentialitateRoute
  '/cont': typeof ContRoute
  '/contact': typeof ContactRoute
  '/cos': typeof CosRoute
  '/despre': typeof DespreRoute
  '/dezabonare': typeof DezabonareRoute
  '/livrare': typeof LivrareRoute
  '/magazin': typeof MagazinRoute
  '/parola-noua': typeof ParolaNouaRoute
  '/produse': typeof ProduseRoute
  '/resetare-parola': typeof ResetareParolaRoute
  '/retur': typeof ReturRoute
  '/retururi': typeof RetururiRoute
  '/termeni': typeof TermeniRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/comanda/$number': typeof ComandaNumberRoute
  '/n7q4-v2m9/audit': typeof N7q4V2m9AuditRoute
  '/n7q4-v2m9/categories': typeof N7q4V2m9CategoriesRoute
  '/n7q4-v2m9/clienti': typeof N7q4V2m9ClientiRoute
  '/n7q4-v2m9/content': typeof N7q4V2m9ContentRoute
  '/n7q4-v2m9/guide': typeof N7q4V2m9GuideRoute
  '/n7q4-v2m9/mesaje': typeof N7q4V2m9MesajeRoute
  '/n7q4-v2m9/orders': typeof N7q4V2m9OrdersRoute
  '/n7q4-v2m9/products': typeof N7q4V2m9ProductsRoute
  '/n7q4-v2m9/retururi': typeof N7q4V2m9RetururiRoute
  '/n7q4-v2m9/roluri': typeof N7q4V2m9RoluriRoute
  '/n7q4-v2m9/setari': typeof N7q4V2m9SetariRoute
  '/n7q4-v2m9/stoc': typeof N7q4V2m9StocRoute
  '/n7q4-v2m9/utilizatori': typeof N7q4V2m9UtilizatoriRoute
  '/produs/$slug': typeof ProdusSlugRoute
  '/staff/categorii': typeof StaffCategoriiRoute
  '/staff/comenzi': typeof StaffComenziRoute
  '/staff/mesaje': typeof StaffMesajeRoute
  '/staff/produse': typeof StaffProduseRoute
  '/staff/retururi': typeof StaffRetururiRoute
  '/staff/stoc': typeof StaffStocRoute
  '/n7q4-v2m9': typeof N7q4V2m9IndexRoute
  '/staff': typeof StaffIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/password-reset': typeof ApiAuthPasswordResetRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ajutor-comanda': typeof AjutorComandaRoute
  '/autentificare': typeof AutentificareRoute
  '/checkout': typeof CheckoutRoute
  '/comenzile-mele': typeof ComenzileMeleRoute
  '/confidentialitate': typeof ConfidentialitateRoute
  '/cont': typeof ContRoute
  '/contact': typeof ContactRoute
  '/cos': typeof CosRoute
  '/despre': typeof DespreRoute
  '/dezabonare': typeof DezabonareRoute
  '/livrare': typeof LivrareRoute
  '/magazin': typeof MagazinRoute
  '/n7q4-v2m9': typeof N7q4V2m9RouteWithChildren
  '/parola-noua': typeof ParolaNouaRoute
  '/produse': typeof ProduseRoute
  '/resetare-parola': typeof ResetareParolaRoute
  '/retur': typeof ReturRoute
  '/retururi': typeof RetururiRoute
  '/staff': typeof StaffRouteWithChildren
  '/termeni': typeof TermeniRoute
  '/categorie/$slug': typeof CategorieSlugRoute
  '/comanda/$number': typeof ComandaNumberRoute
  '/n7q4-v2m9/audit': typeof N7q4V2m9AuditRoute
  '/n7q4-v2m9/categories': typeof N7q4V2m9CategoriesRoute
  '/n7q4-v2m9/clienti': typeof N7q4V2m9ClientiRoute
  '/n7q4-v2m9/content': typeof N7q4V2m9ContentRoute
  '/n7q4-v2m9/guide': typeof N7q4V2m9GuideRoute
  '/n7q4-v2m9/mesaje': typeof N7q4V2m9MesajeRoute
  '/n7q4-v2m9/orders': typeof N7q4V2m9OrdersRoute
  '/n7q4-v2m9/products': typeof N7q4V2m9ProductsRoute
  '/n7q4-v2m9/retururi': typeof N7q4V2m9RetururiRoute
  '/n7q4-v2m9/roluri': typeof N7q4V2m9RoluriRoute
  '/n7q4-v2m9/setari': typeof N7q4V2m9SetariRoute
  '/n7q4-v2m9/stoc': typeof N7q4V2m9StocRoute
  '/n7q4-v2m9/utilizatori': typeof N7q4V2m9UtilizatoriRoute
  '/produs/$slug': typeof ProdusSlugRoute
  '/staff/categorii': typeof StaffCategoriiRoute
  '/staff/comenzi': typeof StaffComenziRoute
  '/staff/mesaje': typeof StaffMesajeRoute
  '/staff/produse': typeof StaffProduseRoute
  '/staff/retururi': typeof StaffRetururiRoute
  '/staff/stoc': typeof StaffStocRoute
  '/n7q4-v2m9/': typeof N7q4V2m9IndexRoute
  '/staff/': typeof StaffIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/password-reset': typeof ApiAuthPasswordResetRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ajutor-comanda'
    | '/autentificare'
    | '/checkout'
    | '/comenzile-mele'
    | '/confidentialitate'
    | '/cont'
    | '/contact'
    | '/cos'
    | '/despre'
    | '/dezabonare'
    | '/livrare'
    | '/magazin'
    | '/n7q4-v2m9'
    | '/parola-noua'
    | '/produse'
    | '/resetare-parola'
    | '/retur'
    | '/retururi'
    | '/staff'
    | '/termeni'
    | '/categorie/$slug'
    | '/comanda/$number'
    | '/n7q4-v2m9/audit'
    | '/n7q4-v2m9/categories'
    | '/n7q4-v2m9/clienti'
    | '/n7q4-v2m9/content'
    | '/n7q4-v2m9/guide'
    | '/n7q4-v2m9/mesaje'
    | '/n7q4-v2m9/orders'
    | '/n7q4-v2m9/products'
    | '/n7q4-v2m9/retururi'
    | '/n7q4-v2m9/roluri'
    | '/n7q4-v2m9/setari'
    | '/n7q4-v2m9/stoc'
    | '/n7q4-v2m9/utilizatori'
    | '/produs/$slug'
    | '/staff/categorii'
    | '/staff/comenzi'
    | '/staff/mesaje'
    | '/staff/produse'
    | '/staff/retururi'
    | '/staff/stoc'
    | '/n7q4-v2m9/'
    | '/staff/'
    | '/api/auth/login'
    | '/api/auth/password-reset'
    | '/api/public/img/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ajutor-comanda'
    | '/autentificare'
    | '/checkout'
    | '/comenzile-mele'
    | '/confidentialitate'
    | '/cont'
    | '/contact'
    | '/cos'
    | '/despre'
    | '/dezabonare'
    | '/livrare'
    | '/magazin'
    | '/parola-noua'
    | '/produse'
    | '/resetare-parola'
    | '/retur'
    | '/retururi'
    | '/termeni'
    | '/categorie/$slug'
    | '/comanda/$number'
    | '/n7q4-v2m9/audit'
    | '/n7q4-v2m9/categories'
    | '/n7q4-v2m9/clienti'
    | '/n7q4-v2m9/content'
    | '/n7q4-v2m9/guide'
    | '/n7q4-v2m9/mesaje'
    | '/n7q4-v2m9/orders'
    | '/n7q4-v2m9/products'
    | '/n7q4-v2m9/retururi'
    | '/n7q4-v2m9/roluri'
    | '/n7q4-v2m9/setari'
    | '/n7q4-v2m9/stoc'
    | '/n7q4-v2m9/utilizatori'
    | '/produs/$slug'
    | '/staff/categorii'
    | '/staff/comenzi'
    | '/staff/mesaje'
    | '/staff/produse'
    | '/staff/retururi'
    | '/staff/stoc'
    | '/n7q4-v2m9'
    | '/staff'
    | '/api/auth/login'
    | '/api/auth/password-reset'
    | '/api/public/img/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ajutor-comanda'
    | '/autentificare'
    | '/checkout'
    | '/comenzile-mele'
    | '/confidentialitate'
    | '/cont'
    | '/contact'
    | '/cos'
    | '/despre'
    | '/dezabonare'
    | '/livrare'
    | '/magazin'
    | '/n7q4-v2m9'
    | '/parola-noua'
    | '/produse'
    | '/resetare-parola'
    | '/retur'
    | '/retururi'
    | '/staff'
    | '/termeni'
    | '/categorie/$slug'
    | '/comanda/$number'
    | '/n7q4-v2m9/audit'
    | '/n7q4-v2m9/categories'
    | '/n7q4-v2m9/clienti'
    | '/n7q4-v2m9/content'
    | '/n7q4-v2m9/guide'
    | '/n7q4-v2m9/mesaje'
    | '/n7q4-v2m9/orders'
    | '/n7q4-v2m9/products'
    | '/n7q4-v2m9/retururi'
    | '/n7q4-v2m9/roluri'
    | '/n7q4-v2m9/setari'
    | '/n7q4-v2m9/stoc'
    | '/n7q4-v2m9/utilizatori'
    | '/produs/$slug'
    | '/staff/categorii'
    | '/staff/comenzi'
    | '/staff/mesaje'
    | '/staff/produse'
    | '/staff/retururi'
    | '/staff/stoc'
    | '/n7q4-v2m9/'
    | '/staff/'
    | '/api/auth/login'
    | '/api/auth/password-reset'
    | '/api/public/img/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AjutorComandaRoute: typeof AjutorComandaRoute
  AutentificareRoute: typeof AutentificareRoute
  CheckoutRoute: typeof CheckoutRoute
  ComenzileMeleRoute: typeof ComenzileMeleRoute
  ConfidentialitateRoute: typeof ConfidentialitateRoute
  ContRoute: typeof ContRoute
  ContactRoute: typeof ContactRoute
  CosRoute: typeof CosRoute
  DespreRoute: typeof DespreRoute
  DezabonareRoute: typeof DezabonareRoute
  LivrareRoute: typeof LivrareRoute
  MagazinRoute: typeof MagazinRoute
  N7q4V2m9Route: typeof N7q4V2m9RouteWithChildren
  ParolaNouaRoute: typeof ParolaNouaRoute
  ProduseRoute: typeof ProduseRoute
  ResetareParolaRoute: typeof ResetareParolaRoute
  ReturRoute: typeof ReturRoute
  RetururiRoute: typeof RetururiRoute
  StaffRoute: typeof StaffRouteWithChildren
  TermeniRoute: typeof TermeniRoute
  CategorieSlugRoute: typeof CategorieSlugRoute
  ComandaNumberRoute: typeof ComandaNumberRoute
  ProdusSlugRoute: typeof ProdusSlugRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthPasswordResetRoute: typeof ApiAuthPasswordResetRoute
  ApiPublicImgSplatRoute: typeof ApiPublicImgSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajutor-comanda': {
      id: '/ajutor-comanda'
      path: '/ajutor-comanda'
      fullPath: '/ajutor-comanda'
      preLoaderRoute: typeof AjutorComandaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autentificare': {
      id: '/autentificare'
      path: '/autentificare'
      fullPath: '/autentificare'
      preLoaderRoute: typeof AutentificareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comenzile-mele': {
      id: '/comenzile-mele'
      path: '/comenzile-mele'
      fullPath: '/comenzile-mele'
      preLoaderRoute: typeof ComenzileMeleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialitate': {
      id: '/confidentialitate'
      path: '/confidentialitate'
      fullPath: '/confidentialitate'
      preLoaderRoute: typeof ConfidentialitateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cont': {
      id: '/cont'
      path: '/cont'
      fullPath: '/cont'
      preLoaderRoute: typeof ContRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cos': {
      id: '/cos'
      path: '/cos'
      fullPath: '/cos'
      preLoaderRoute: typeof CosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despre': {
      id: '/despre'
      path: '/despre'
      fullPath: '/despre'
      preLoaderRoute: typeof DespreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dezabonare': {
      id: '/dezabonare'
      path: '/dezabonare'
      fullPath: '/dezabonare'
      preLoaderRoute: typeof DezabonareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livrare': {
      id: '/livrare'
      path: '/livrare'
      fullPath: '/livrare'
      preLoaderRoute: typeof LivrareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magazin': {
      id: '/magazin'
      path: '/magazin'
      fullPath: '/magazin'
      preLoaderRoute: typeof MagazinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n7q4-v2m9': {
      id: '/n7q4-v2m9'
      path: '/n7q4-v2m9'
      fullPath: '/n7q4-v2m9'
      preLoaderRoute: typeof N7q4V2m9RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parola-noua': {
      id: '/parola-noua'
      path: '/parola-noua'
      fullPath: '/parola-noua'
      preLoaderRoute: typeof ParolaNouaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produse': {
      id: '/produse'
      path: '/produse'
      fullPath: '/produse'
      preLoaderRoute: typeof ProduseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resetare-parola': {
      id: '/resetare-parola'
      path: '/resetare-parola'
      fullPath: '/resetare-parola'
      preLoaderRoute: typeof ResetareParolaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retur': {
      id: '/retur'
      path: '/retur'
      fullPath: '/retur'
      preLoaderRoute: typeof ReturRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retururi': {
      id: '/retururi'
      path: '/retururi'
      fullPath: '/retururi'
      preLoaderRoute: typeof RetururiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termeni': {
      id: '/termeni'
      path: '/termeni'
      fullPath: '/termeni'
      preLoaderRoute: typeof TermeniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorie/$slug': {
      id: '/categorie/$slug'
      path: '/categorie/$slug'
      fullPath: '/categorie/$slug'
      preLoaderRoute: typeof CategorieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comanda/$number': {
      id: '/comanda/$number'
      path: '/comanda/$number'
      fullPath: '/comanda/$number'
      preLoaderRoute: typeof ComandaNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n7q4-v2m9/': {
      id: '/n7q4-v2m9/'
      path: '/'
      fullPath: '/n7q4-v2m9/'
      preLoaderRoute: typeof N7q4V2m9IndexRouteImport
      parentRoute: typeof N7q4V2m9Route
    }
    '/n7q4-v2m9/audit': {
      id: '/n7q4-v2m9/audit'
      path: '/audit'
      fullPath: '/n7q4-v2m9/audit'
      preLoaderRoute: typeof N7q4V2m9AuditRouteImport
      parentRoute: typeof N7q4V2m9Route
    }
    '/n7q4-v2m9/categories': {
      id: '/n7q4-v2m9/categories'
      path: '/categories'
      fullPath: '/n7q4-v2m9/categories'
      preLoaderRoute: typeof N7q4V2m9CategoriesRouteImport
      parentRoute: typeof N7q4V2m9Route
    }
    '/n7q4-v2m9/clienti': {
      id: '/n7q4-v2m9/clienti'
      path: '/clienti'
      fullPath: '/n7q4-v2m9/clienti'
      preLoaderRoute: typeof N7q4V2m9ClientiRouteImport
      parentRoute: typeof N7q4V2m9Route
    }
    '/n7q4-v2m9/content': {
      id: '/n7q4-v2m9/content'
      path: '/content'
      fullPath: '/n7q4-v2m9/content'
      preLoaderRoute: typeof N7q4V2m9ContentRouteImport
      parentRoute: typeof N7q4V2m9Route
    }
    '/n7q4-v2m9/guide': {
      id: '/n7q4-v2m9/guide'
      path: '/guide'
      fullPath: '/n7q4-v2m9/guide'
      preLoaderRoute: typeof N7q4V2m9GuideRouteImport
      parentRoute: typeof N7q4V2m9Route
    }
    '/n7q4-v2m9/mesaje': {
      id: '/n7q4-v2m9/mesaje'
      path: '/mesaje'
      fullPath: '/n7q4-v2m9/mesaje'
      preLoaderRoute: typeof N7q4V2m9MesajeRouteImport
      parentRoute: typeof N7q4V2m9Route
    }
    '/n7q4-v2m9/orders': {
      id: '/n7q4-v2m9/orders'
      path: '/orders'
      fullPath: '/n7q4-v2m9/orders'
      preLoaderRoute: typeof N7q4V2m9OrdersRouteImport
      parentRoute: typeof N7q4V2m9Route
    }
    '/n7q4-v2m9/products': {
      id: '/n7q4-v2m9/products'
      path: '/products'
      fullPath: '/n7q4-v2m9/products'
      preLoaderRoute: typeof N7q4V2m9ProductsRouteImport
      parentRoute: typeof N7q4V2m9Route
    }
    '/n7q4-v2m9/retururi': {
      id: '/n7q4-v2m9/retururi'
      path: '/retururi'
      fullPath: '/n7q4-v2m9/retururi'
      preLoaderRoute: typeof N7q4V2m9RetururiRouteImport
      parentRoute: typeof N7q4V2m9Route
    }
    '/n7q4-v2m9/roluri': {
      id: '/n7q4-v2m9/roluri'
      path: '/roluri'
      fullPath: '/n7q4-v2m9/roluri'
      preLoaderRoute: typeof N7q4V2m9RoluriRouteImport
      parentRoute: typeof N7q4V2m9Route
    }
    '/n7q4-v2m9/setari': {
      id: '/n7q4-v2m9/setari'
      path: '/setari'
      fullPath: '/n7q4-v2m9/setari'
      preLoaderRoute: typeof N7q4V2m9SetariRouteImport
      parentRoute: typeof N7q4V2m9Route
    }
    '/n7q4-v2m9/stoc': {
      id: '/n7q4-v2m9/stoc'
      path: '/stoc'
      fullPath: '/n7q4-v2m9/stoc'
      preLoaderRoute: typeof N7q4V2m9StocRouteImport
      parentRoute: typeof N7q4V2m9Route
    }
    '/n7q4-v2m9/utilizatori': {
      id: '/n7q4-v2m9/utilizatori'
      path: '/utilizatori'
      fullPath: '/n7q4-v2m9/utilizatori'
      preLoaderRoute: typeof N7q4V2m9UtilizatoriRouteImport
      parentRoute: typeof N7q4V2m9Route
    }
    '/produs/$slug': {
      id: '/produs/$slug'
      path: '/produs/$slug'
      fullPath: '/produs/$slug'
      preLoaderRoute: typeof ProdusSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/categorii': {
      id: '/staff/categorii'
      path: '/categorii'
      fullPath: '/staff/categorii'
      preLoaderRoute: typeof StaffCategoriiRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/comenzi': {
      id: '/staff/comenzi'
      path: '/comenzi'
      fullPath: '/staff/comenzi'
      preLoaderRoute: typeof StaffComenziRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/mesaje': {
      id: '/staff/mesaje'
      path: '/mesaje'
      fullPath: '/staff/mesaje'
      preLoaderRoute: typeof StaffMesajeRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/produse': {
      id: '/staff/produse'
      path: '/produse'
      fullPath: '/staff/produse'
      preLoaderRoute: typeof StaffProduseRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/retururi': {
      id: '/staff/retururi'
      path: '/retururi'
      fullPath: '/staff/retururi'
      preLoaderRoute: typeof StaffRetururiRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/stoc': {
      id: '/staff/stoc'
      path: '/stoc'
      fullPath: '/staff/stoc'
      preLoaderRoute: typeof StaffStocRouteImport
      parentRoute: typeof StaffRoute
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/password-reset': {
      id: '/api/auth/password-reset'
      path: '/api/auth/password-reset'
      fullPath: '/api/auth/password-reset'
      preLoaderRoute: typeof ApiAuthPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/img/$': {
      id: '/api/public/img/$'
      path: '/api/public/img/$'
      fullPath: '/api/public/img/$'
      preLoaderRoute: typeof ApiPublicImgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface N7q4V2m9RouteChildren {
  N7q4V2m9AuditRoute: typeof N7q4V2m9AuditRoute
  N7q4V2m9CategoriesRoute: typeof N7q4V2m9CategoriesRoute
  N7q4V2m9ClientiRoute: typeof N7q4V2m9ClientiRoute
  N7q4V2m9ContentRoute: typeof N7q4V2m9ContentRoute
  N7q4V2m9GuideRoute: typeof N7q4V2m9GuideRoute
  N7q4V2m9MesajeRoute: typeof N7q4V2m9MesajeRoute
  N7q4V2m9OrdersRoute: typeof N7q4V2m9OrdersRoute
  N7q4V2m9ProductsRoute: typeof N7q4V2m9ProductsRoute
  N7q4V2m9RetururiRoute: typeof N7q4V2m9RetururiRoute
  N7q4V2m9RoluriRoute: typeof N7q4V2m9RoluriRoute
  N7q4V2m9SetariRoute: typeof N7q4V2m9SetariRoute
  N7q4V2m9StocRoute: typeof N7q4V2m9StocRoute
  N7q4V2m9UtilizatoriRoute: typeof N7q4V2m9UtilizatoriRoute
  N7q4V2m9IndexRoute: typeof N7q4V2m9IndexRoute
}

const N7q4V2m9RouteChildren: N7q4V2m9RouteChildren = {
  N7q4V2m9AuditRoute: N7q4V2m9AuditRoute,
  N7q4V2m9CategoriesRoute: N7q4V2m9CategoriesRoute,
  N7q4V2m9ClientiRoute: N7q4V2m9ClientiRoute,
  N7q4V2m9ContentRoute: N7q4V2m9ContentRoute,
  N7q4V2m9GuideRoute: N7q4V2m9GuideRoute,
  N7q4V2m9MesajeRoute: N7q4V2m9MesajeRoute,
  N7q4V2m9OrdersRoute: N7q4V2m9OrdersRoute,
  N7q4V2m9ProductsRoute: N7q4V2m9ProductsRoute,
  N7q4V2m9RetururiRoute: N7q4V2m9RetururiRoute,
  N7q4V2m9RoluriRoute: N7q4V2m9RoluriRoute,
  N7q4V2m9SetariRoute: N7q4V2m9SetariRoute,
  N7q4V2m9StocRoute: N7q4V2m9StocRoute,
  N7q4V2m9UtilizatoriRoute: N7q4V2m9UtilizatoriRoute,
  N7q4V2m9IndexRoute: N7q4V2m9IndexRoute,
}

const N7q4V2m9RouteWithChildren = N7q4V2m9Route._addFileChildren(
  N7q4V2m9RouteChildren,
)

interface StaffRouteChildren {
  StaffCategoriiRoute: typeof StaffCategoriiRoute
  StaffComenziRoute: typeof StaffComenziRoute
  StaffMesajeRoute: typeof StaffMesajeRoute
  StaffProduseRoute: typeof StaffProduseRoute
  StaffRetururiRoute: typeof StaffRetururiRoute
  StaffStocRoute: typeof StaffStocRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffCategoriiRoute: StaffCategoriiRoute,
  StaffComenziRoute: StaffComenziRoute,
  StaffMesajeRoute: StaffMesajeRoute,
  StaffProduseRoute: StaffProduseRoute,
  StaffRetururiRoute: StaffRetururiRoute,
  StaffStocRoute: StaffStocRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AjutorComandaRoute: AjutorComandaRoute,
  AutentificareRoute: AutentificareRoute,
  CheckoutRoute: CheckoutRoute,
  ComenzileMeleRoute: ComenzileMeleRoute,
  ConfidentialitateRoute: ConfidentialitateRoute,
  ContRoute: ContRoute,
  ContactRoute: ContactRoute,
  CosRoute: CosRoute,
  DespreRoute: DespreRoute,
  DezabonareRoute: DezabonareRoute,
  LivrareRoute: LivrareRoute,
  MagazinRoute: MagazinRoute,
  N7q4V2m9Route: N7q4V2m9RouteWithChildren,
  ParolaNouaRoute: ParolaNouaRoute,
  ProduseRoute: ProduseRoute,
  ResetareParolaRoute: ResetareParolaRoute,
  ReturRoute: ReturRoute,
  RetururiRoute: RetururiRoute,
  StaffRoute: StaffRouteWithChildren,
  TermeniRoute: TermeniRoute,
  CategorieSlugRoute: CategorieSlugRoute,
  ComandaNumberRoute: ComandaNumberRoute,
  ProdusSlugRoute: ProdusSlugRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthPasswordResetRoute: ApiAuthPasswordResetRoute,
  ApiPublicImgSplatRoute: ApiPublicImgSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
